
package com.emre.staffmanagement;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "employeeManagementWebService", targetNamespace = "http://staffmanagement.emre.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeManagementWebService {


    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dummy", targetNamespace = "http://staffmanagement.emre.com/", className = "com.emre.staffmanagement.Dummy")
    @ResponseWrapper(localName = "dummyResponse", targetNamespace = "http://staffmanagement.emre.com/", className = "com.emre.staffmanagement.DummyResponse")
    public double dummy();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.emre.staffmanagement.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchBySurname", targetNamespace = "http://staffmanagement.emre.com/", className = "com.emre.staffmanagement.SearchBySurname")
    @ResponseWrapper(localName = "searchBySurnameResponse", targetNamespace = "http://staffmanagement.emre.com/", className = "com.emre.staffmanagement.SearchBySurnameResponse")
    public List<Employee> searchBySurname(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.emre.staffmanagement.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllEmployees", targetNamespace = "http://staffmanagement.emre.com/", className = "com.emre.staffmanagement.GetAllEmployees")
    @ResponseWrapper(localName = "getAllEmployeesResponse", targetNamespace = "http://staffmanagement.emre.com/", className = "com.emre.staffmanagement.GetAllEmployeesResponse")
    public List<Employee> getAllEmployees();

    /**
     * 
     * @param arg0
     * @throws SystemUnavaliableException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "registerEmployee", targetNamespace = "http://staffmanagement.emre.com/", className = "com.emre.staffmanagement.RegisterEmployee")
    @ResponseWrapper(localName = "registerEmployeeResponse", targetNamespace = "http://staffmanagement.emre.com/", className = "com.emre.staffmanagement.RegisterEmployeeResponse")
    public void registerEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0)
        throws SystemUnavaliableException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws SystemUnavaliableException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "rollbackCheckedException", targetNamespace = "http://staffmanagement.emre.com/", className = "com.emre.staffmanagement.RollbackCheckedException")
    @ResponseWrapper(localName = "rollbackCheckedExceptionResponse", targetNamespace = "http://staffmanagement.emre.com/", className = "com.emre.staffmanagement.RollbackCheckedExceptionResponse")
    public void rollbackCheckedException(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0)
        throws SystemUnavaliableException_Exception
    ;

}
